#ifndef PGBIGNUMBER_PARALLEL_FWD_H
#define PGBIGNUMBER_PARALLEL_FWD_H

#include "../fwd.h"

#define PGBN_PARALLEL_NAMESPACE_START PGBN_NAMESPACE_START namespace parallel {
#define PGBN_PARALLEL_NAMESPACE_END } PGBN_NAMESPACE_END

PGBN_PARALLEL_NAMESPACE_START

using RawTask = std::function<void()>;

PGBN_PARALLEL_NAMESPACE_END
#endif // !PGBIGNUMBER_PARALLEL_FWD_H
